### ISSUE TITLE
If a user creates a second repos folder with the same XML file name it will cause the backend to crash

### ISSUE THREAD

**Issue by grantcurell** [dell/patches#13]
I have two separate folders 'Enterprise Server Catalog-23.07.07'  'Enterprise Server Catalog-23.08.11' however they both have the XML name patches_1.00_Catalog.xml. This causes:

Uncaught DatabaseError error: insert into "xml_files" ("file_name", "file_path") values ($1, $2) on conflict ("file_path") do nothing - duplicate key value violates unique constraint "xml_files_file_name_unique"
    at parseErrorMessage (c:\Users\grant\Documents\code\dell-patches\node_modules\pg-protocol\dist\parser.js:287:98)
    at handlePacket (c:\Users\grant\Documents\code\dell-patches\node_modules\pg-protocol\dist\parser.js:126:29)
    at parse (c:\Users\grant\Documents\code\dell-patches\node_modules\pg-protocol\dist\parser.js:39:38)
    at <anonymous> (c:\Users\grant\Documents\code\dell-patches\node_modules\pg-protocol\dist\index.js:11:42)
    at emit (events:514:28)
    at addChunk (internal/streams/readable:324:12)
    at readableAddChunk (internal/streams/readable:297:9)
    at Readable.push (internal/streams/readable:234:10)
    at onStreamRead (internal/stream_base_commons:190:23)
    at callbackTrampoline (internal/async_hooks:130:17)

**Comment by grantcurell** [comment]
Current fix action is to change one of the XML names
